version: '3.9'
services:
  db:
    container_name: docker_scraper_db
    image: postgres:15.2-alpine
    environment:
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_DB=main'
    ports:
      - '5432:5432'
    volumes:
      - 'db_data:/var/lib/postgresql/data'
    healthcheck:
      test: 'pg_isready -U root -d main'
      interval: 5s
      timeout: 5s
      retries: 3
  scraper:
    container_name: docker_scraper_scraper
    build: ./scraper
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URI: 'postgresql+psycopg2://root:root@db:5432/main'
      MAX_ITEM_COUNT: '500'
  app:
    container_name: docker_scraper_app
    build: ./app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URI: 'postgresql+psycopg2://root:root@db:5432/main'
      SERVER_NAME: '0.0.0.0:8080'
    ports:
      - '8080:8080'
volumes:
  db_data:
    driver: local
